version: "3.8"

services:
  app:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: app
    image: fullcycle/php
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
        - app-php

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - "8888:80"
        - "445:443"
    volumes:
        - ./:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - app-php
networks:
    app-php:
        driver: bridge

